### ISSUE TITLE
Disable Other Blocked Tiles

### ISSUE THREAD

**Issue by Norkotah** [WhatATopic/StopMisclickingTiles#5]
What exactly does this option do? The Plugin Hub info page doesn't mention it, and the hover text is pretty vague.

**Comment by WhatATopic** [comment]
The collision flags aren't explained very well in the Runelite API but essentially there are some tiles that you cannot stand on because they are blocked by an object like a crate or something. Then there are other tiles like walls and water that don't have objects on them but you still cannot stand on them. So this config option allows you to prevent clicking on those kinds of tiles. I've used this option when fighting Zulrah because I would sometimes misclick while trying to attack and clicking the water surrounding the boss would cause my character to move out of the safe spot and potentially stand inside the venom clouds. I hope this explains the option well enough.

**Comment by Norkotah** [comment]
Thank you for the insanely fast reply and for the information you provided. This is exactly what I wanted to know.
